// Autogenerated from Pigeon (v1.0.12), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FLTVideoEditResult;

@interface FLTVideoEditResult : NSObject
@property(nonatomic, copy, nullable) NSString * filepath;
@end

/// The codec used by FLTBanubaVideoEditorApi.
NSObject<FlutterMessageCodec> *FLTBanubaVideoEditorApiGetCodec(void);

@protocol FLTBanubaVideoEditorApi
- (void)startEditorFromCameraWithCompletion:(void(^)(FLTVideoEditResult *_Nullable, FlutterError *_Nullable))completion;
@end

extern void FLTBanubaVideoEditorApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTBanubaVideoEditorApi> *_Nullable api);

NS_ASSUME_NONNULL_END
