// Autogenerated from Pigeon (v1.0.12), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "BanubaVideoEditorPluginApi.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ? error.code : [NSNull null]),
        @"message": (error.message ? error.message : [NSNull null]),
        @"details": (error.details ? error.details : [NSNull null]),
        };
  }
  return @{
      @"result": (result ? result : [NSNull null]),
      @"error": errorDict,
      };
}

@interface FLTVideoEditResult ()
+ (FLTVideoEditResult *)fromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end

@implementation FLTVideoEditResult
+ (FLTVideoEditResult *)fromMap:(NSDictionary *)dict {
  FLTVideoEditResult *result = [[FLTVideoEditResult alloc] init];
  result.filePath = dict[@"filePath"];
  if ((NSNull *)result.filePath == [NSNull null]) {
    result.filePath = nil;
  }
  result.coverPath = dict[@"coverPath"];
  if ((NSNull *)result.coverPath == [NSNull null]) {
    result.coverPath = nil;
  }
  return result;
}
- (NSDictionary *)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.filePath ? self.filePath : [NSNull null]), @"filePath", (self.coverPath ? self.coverPath : [NSNull null]), @"coverPath", nil];
}
@end

@interface FLTBanubaVideoEditorApiCodecReader : FlutterStandardReader
@end
@implementation FLTBanubaVideoEditorApiCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [FLTVideoEditResult fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface FLTBanubaVideoEditorApiCodecWriter : FlutterStandardWriter
@end
@implementation FLTBanubaVideoEditorApiCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[FLTVideoEditResult class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface FLTBanubaVideoEditorApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation FLTBanubaVideoEditorApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[FLTBanubaVideoEditorApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[FLTBanubaVideoEditorApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *FLTBanubaVideoEditorApiGetCodec() {
  static dispatch_once_t s_pred = 0;
  static FlutterStandardMessageCodec *s_sharedObject = nil;
  dispatch_once(&s_pred, ^{
    FLTBanubaVideoEditorApiCodecReaderWriter *readerWriter = [[FLTBanubaVideoEditorApiCodecReaderWriter alloc] init];
    s_sharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return s_sharedObject;
}


void FLTBanubaVideoEditorApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTBanubaVideoEditorApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.BanubaVideoEditorApi.startEditorFromCamera"
        binaryMessenger:binaryMessenger
        codec:FLTBanubaVideoEditorApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(startEditorFromCameraWithCompletion:)], @"FLTBanubaVideoEditorApi api (%@) doesn't respond to @selector(startEditorFromCameraWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api startEditorFromCameraWithCompletion:^(FLTVideoEditResult *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
