name: banuba_video_editor
description: A new flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.levl.banuba.banuba_video_editor
        pluginClass: BanubaVideoEditorPlugin
      ios:
        pluginClass: BanubaVideoEditorPlugin
